name: publish
on: [push]
jobs:
  publish-docker-image:
    name: publish cloud-sdk-ksops
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the google cloudsdk image with ksops
        run: |
            docker build . --tag ghcr.io/atbore-phx/cloud-sdk-ksops:latest
            docker push ghcr.io/atbore-phx/cloud-sdk-ksops:latest
